services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ai-security-open-webui

    ports:
      - "${OPEN_WEBUI_PORT}:8080"

    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - RAG_OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - RAG_EMBEDDING_ENGINE=${RAG_EMBEDDING_ENGINE}
      - RAG_EMBEDDING_MODEL=${RAG_EMBEDDING_MODEL}
      - RAG_RERANKING_ENGINE=${RAG_RERANKING_ENGINE}
      - RAG_RERANKING_MODEL=${RAG_RERANKING_MODEL}
      - RAG_TOP_K=${RAG_TOP_K}
      - RAG_TOP_K_RERANKER=${RAG_TOP_K_RERANKER}


    volumes:
      - ./open-webui-data:/app/backend/data

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

